[printer]
[printer.default]
ip = "192.168.1.37" # IP Addr for SGD commands, jetdirect, FTP
port = 9100 # Port for SGD/Jetdirect commands
[printer.qln220] # Specify multiple printers like this
ip = "192.168.1.200"
[style] # The style section determines how the output of the message subcommand is formatted
[style.qln220] # You can specify multiple styles and select with the -s flag
font_size = 35
font_width = 35
start_point = 10 # the initial y-axis starting point on the label
line_padding = 0 # The amount of additional padding inserted between lines
invert = true #Rotate the label 180 degrees
font = "E"
precommand = "setvar ezpl.print_width 200" # an optional field that will run the given command before the message is printed
[style.default]
font_size = 60
font_width = 60
line_padding = 10
indent = 15
invert = false
font = "0"